# Generated by Django 5.0.6 on 2024-07-06 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plantas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomnbre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.plantas')),
            ],
        ),
        migrations.CreateModel(
            name='Registro_Produccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_combustible', models.CharField(max_length=10)),
                ('litros_producidos', models.IntegerField(default=0)),
                ('fecha_produccion', models.DateField()),
                ('turno', models.CharField(choices=[('AM', 'Mañana'), ('PM', 'Tarde'), ('MM', 'Noche')], max_length=2)),
                ('hora_registro', models.TimeField()),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='registros_creados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros_modificados', to=settings.AUTH_USER_MODEL)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_operador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
