# Generated by Django 5.0.6 on 2024-07-06 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_operador', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plantas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_planta', models.CharField(max_length=100)),
                ('codigo_planta', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('nombre_producto', models.CharField(max_length=100)),
                ('codigo_producto', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nombre_planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.plantas')),
            ],
        ),
        migrations.CreateModel(
            name='Registro_Produccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('litros_produccion', models.FloatField()),
                ('fecha_produccion', models.DateField()),
                ('turno', models.CharField(choices=[('mañana', 'AM'), ('tarde', 'PM'), ('noche', 'MM')], max_length=6)),
                ('hora_registro', models.TimeField()),
                ('codigo_combustible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.productos')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.operador')),
            ],
        ),
    ]
