# Generated by Django 5.0.6 on 2024-07-06 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_rename_nomnbre_plantas_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operador',
            old_name='nombre',
            new_name='nombre_operador',
        ),
    ]
