# Generated by Django 5.0.6 on 2024-07-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_registro_produccion_anulado_anulacionhistorial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anulacionhistorial',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='anulacionhistorial',
            name='anulado_por',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
