# Generated by Django 5.0.6 on 2024-07-07 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_anulacionhistorial_supervisor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registro_produccion',
            name='modificado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registro_produccion',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registro_produccion',
            name='fecha_produccion',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='registro_produccion',
            name='hora_registro',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='registro_produccion',
            name='turno',
            field=models.CharField(choices=[('AM', 'AM'), ('PM', 'PM'), ('MM', 'MM')], max_length=2),
        ),
        migrations.CreateModel(
            name='RegistroModificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True)),
                ('datos_antes', models.TextField()),
                ('modificado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.registro_produccion')),
            ],
        ),
    ]
